### ISSUE TITLE
403 Forbidden  https://cloud.mail.ru/api/v2/file/publish

### ISSUE THREAD

**Issue by kbace4ka** [erastmorgan/MailRuCloudClientDotNETCore#4]
При получении ссылки на каталог я получаю в ответ 403
Они поменяли апи ? Куда копать, что смотреть ?

**Comment by erastmorgan** [comment]
Сам запрос остался тем же, но поменялись параметры передаваемые в теле запроса. Детально не изучал, но сразу же в глаза бросается отсутствие токена авторизации в теле запроса, скорее всего теперь он через куки передается. Еще и на других  вызовах обнаружил разные ошибки. Удивляюсь что вообще либа рабочая еще, учитывая что 2 года я уже не вносил правок).

В ближайшие месяцы постараюсь новую версию библиотеки опубликовать. С текущей доработок уже не будет. Если у самих получится исправить проблему, пожалуйста, присылайте pull request и применим заплатки.

**Comment by djdes** [comment]
@erastmorgan как с вами связаться? Готов оплатить оперативную доработку данной проблемы. моя почта  r12lb3gb@inbox.ru

**Comment by erastmorgan** [comment]
Ответил на почту
